# Generated by Django 2.2.5 on 2020-02-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Light',
            fields=[
                ('light_id', models.AutoField(primary_key=True, serialize=False)),
                ('light_name', models.TextField()),
                ('light_group', models.CharField(choices=[('G1', 'G1'), ('G2', 'G2')], max_length=2)),
            ],
        ),
    ]
